### ISSUE TITLE
Unable to build Disktool5 missing header.h file

### ISSUE THREAD

**Issue by fourstix** [rileym65/ElfosV5#1]
Hi, I'm trying to build the Disktool5 to create an Elfos v5 disk on a CF card.  I cloned this repository to my Raspberry Pi running the Turnkey development disk.

When I run make, I see the following error that the header.h file is missing.   Where should I get the header.h file?  And what directory should this file go into.

Here's the error from the make commad:

pi@turnkey:~/Projects/ElfosV5/Disktool5/Main $ make
gcc    -c ../Common/allocau.c
../Common/allocau.c:1:10: fatal error: header.h: No such file or directory
 #include "header.h"
          ^~~~~~~~~~
compilation terminated.
make: *** [Makefile:53: ../Common/allocau.o] Error 1

**Comment by rileym65** [comment]
I have added the missing header, try pulling the source again.
    Mike
________________________________
From: fourstix ***@***.***>
Sent: Friday, December 22, 2023 10:49 AM
To: rileym65/ElfosV5 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [rileym65/ElfosV5] Unable to build Disktool5 missing header.h file (Issue #1)


Hi, I'm trying to build the Disktool5 to create an Elfos v5 disk on a CF card. I cloned this repository to my Raspberry Pi running the Turnkey development disk.

When I run make, I see the following error that the header.h file is missing. Where should I get the header.h file? And what directory should this file go into.

Here's the error from the make commad:

***@***.***:~/Projects/ElfosV5/Disktool5/Main $ make
gcc -c ../Common/allocau.c
../Common/allocau.c:1:10: fatal error: header.h: No such file or directory
#include "header.h"
^~~~~~~~~~
compilation terminated.
make: *** [Makefile:53: ../Common/allocau.o] Error 1

**Comment by fourstix** [comment]
I just tried it and no changes came in.  Did you push your changes to main?

**Comment by rileym65** [comment]
Looks like I forgot to push it up.  Try it now.
    Mike
________________________________

**Comment by fourstix** [comment]
Wonderful!  That fixed it. Thanks, Mike

**Comment by rileym65** [comment]
So you have it up and running?
________________________________

**Comment by fourstix** [comment]
Hi Mike,

I was able to run make and built all the tools on a Raspberry Pi running the turnkey system.  

I have a brand new 2GB CF card for testing.  I am trying to figure out how to best get started.  I have a USB card reader that I can plug into either my Windows laptop or my Raspberry Pi with the turnkey image.

**Comment by rileym65** [comment]
If you can use your USB card reader to write an image onto a CF card, then your best way to get a system up and running is to use FsGen2 and generate the image on your PC.  For a 2gb filesystem the command should be 'fsgen2 2000' .  Depending on the physical capacity of your CF card, you may have to make that 2000 a little smaller, as long as the final image from FsGen is smaller or equal to the byte capacity of your CF card you will be good to go.

FsGen2 will setup a basic filesystem with the kernel installed, and DIR, CHMOD, CHDIR, XR, and LBR pre-installed.  Using DiskTool5 you can then copy the basetools5.lbr to the /bin directory of your image file, which you can then extract after you boot up the image.  While you are in DiskTool5, you can copy anything else onto your disk image, so far I have tried RcBasicL2, RcForth, RcLisp, RcPilot, RcMouse, RcVtl2, Zrun3, TBC, and SBC, and all ran fine without any issues.
    Mike
________________________________

**Comment by fourstix** [comment]
Hi Mike,
I'm struggling to copy files with disktool5 on to the image.  I can open the image and view it.  But when I try to copy [basetools5.lbr] basetools5.lbr.  I don't see basetools5.lbr in the /bin directory.

Here's a screenshot:


>dir
bin/                os/

>cd bin
Path: bin
DF=0

>copy [./basetools5.lbr] basetools5.lbr
[./basetools5.lbr] --> basetools5.lbr
D = 0f
DF = 1

>dir
dir                 chdir               lbr                 xr
chmod               free

>

Do I have the syntax right?

**Comment by rileym65** [comment]
Yes, it looks like you have the syntax right.  the DF=1 signals an error happened.  This is with a disk image created from FsGen2?  I will try it on my system.
    Mike

________________________________

**Comment by fourstix** [comment]
Hi Mike,
Yes.  The image was created with the command fsgen2 2000.   I then copied the image file disk1.ide to Windows and created the CF card using the Balen Etcher tool.  (I'm not too familiar with dd so I switched to Windows to burn the card.)

I tried both the CF card itself and the disk1.ide file with the disktool5  and I could not copy to either one.

**Comment by rileym65** [comment]
Yep, it fails for me too.  The error is disk full, so it did not find a free au, so there is a bug somewhere, let me do some digging.  Get back to you shortly.
    Mike

________________________________

**Comment by rileym65** [comment]
Looks like there may be an overflow in a variable,  I could copy with no problem onto a 500mb disk, but not 600mb or up.  I will do some digging and see where the issue is.
    Mike
________________________________

**Comment by rileym65** [comment]
I found the problem, give me a few minutes to fix and test it, and then will push a new DiskTool5 to GitHub.
    Mike
________________________________

**Comment by fourstix** [comment]
Great, thank you, Mike!

**Comment by rileym65** [comment]
Ok, fixed the issue with DiskTool5, but that also highlighted a kernel bug I need to fix as well.  After I fix that I will need to create all new installers and push them, so give me a bit and I will let you know when all is done.
    Mike

________________________________

**Comment by rileym65** [comment]
Ok, I have updated FsGen1, FsGen2, and DiskTool5 to fix the issues.  Go ahead and pull everything and try again.  After building your image, inside of DiskTool, you can issue the 'stat' command and it should report that kernel build 156 is installed.
    Mike

________________________________

**Comment by fourstix** [comment]
Great.  I think that fixed it.  I pulled in the changes and cleaned and rebuilt all the tools.  Then I created a new disk image with fsgen2.  I was able to open the image with disktool5 and the stat command reported kernel build 156.  

I was then able to add basetools5.lbr to the bin directory.  Thanks for your help.  I'm currently updating the CF card with the new disk image using the dd command.
